---
title: 叶夕青兮
intro: 生活就是一本书，一壶茶，一个阳光明媚的下午！
production: true
email: zhangshiyu1992@hotmail.com
author: Erl
url: https://erl.im
img_prefix: https://persephone.oss-cn-beijing.aliyuncs.com
github_username: erlzhang
version: v3.5.20190330
sass:
  sass_dir: _sass
markdown: kramdown
permalink: /blog/:title:output_ext
timezone: Asia/Shanghai
excerpt_separator: <!--more-->
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      keywords: 叶夕青兮, 原创独立博客, Erl, Jekyll
      description: 叶夕青兮，目前还是程序员。这里是她的独立博客，分享编程、建站、生活感悟、读书随笔、原创小说等。
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - src
  - package.json
  - package-lock.json
  - webpack.config.js
  - README.md
  - staticman.yml
include:
  - _redirects
  - _headers

comment:
  enabled: true
  postUrl: "https://dev.staticman.net/v3/entry/github/erlzhang/persephone/master/comments"
smiley:
  enabled: true
  dir: "assets/smileys"

pagination:
  enabled: true
  per_page: 5
  indexpage: index
  title: ":title"
  sort_field: date
  sort_reverse: true
  trail:
    before: 2
    after: 2

